version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip3 install -U black flake8 --user
      - run: black --check .
      - run: flake8 .
  build:
    docker:
      - image: circleci/python:3
    steps:
      - run: 
          command: pwd 
      - run: pip3 install -r ~/SeismicMesh/requirements.txt
      - run: pip3 install -U pytest pytest-cov --user
      - checkout
      - run:
          command: pytest --cov SeismicMesh
workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
